services:
  nginx:
    image: nginx:1.27.4-alpine-slim
    container_name: api-gateway
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - USER_SERVICE_PORT=8081
    ports:
      - "8080:80"
    depends_on:
      - user-service
    networks:
      - app-network

  user-service:
    build: ./user-service
    container_name: user-service
    environment:
      - SERVER_PORT=8081
    depends_on:
      - user-db
    networks:
      - app-network

  movie-service:
    build: ./movie-service
    container_name: movie-service
    environment:
      - SERVER_PORT=8091
    depends_on:
      - movie-db
    networks:
      - app-network

  user-db:
    image: postgres:17-alpine
    container_name: user-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=users
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - app-network

  movie-db:
    image: postgres:17-alpine
    container_name: movie-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=movies
    volumes:
      - movie_db_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:8.12.0
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@horines.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:4-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

networks:
  app-network:
    driver: bridge

volumes:
  rabbitmq_data:
  redis_data:
  user_db_data:
  pgadmin_data:
