package org.movies.service.models.people;

public enum Role {
    ACTOR,
    DIRECTOR,
    PRODUCER,
    WRITER,
    CINEMATOGRAPHER,
    EDITOR,
    CASTING_DIRECTOR,
    PRODUCTION_DESIGNER,
    ART_DIRECTOR,
    COSTUME_DESIGNER,
    MAKEUP_ARTIST,
    HAIR_STYLIST,
    SOUND_DESIGNER,
    SOUND_MIXER,
    PRODUCTION_MANAGER,
    STUNT_COORDINATOR,
    STUNT_PERFORMER,
    VISUAL_EFFECTS_SUPERVISOR,
    VFX_ARTIST,
    CAMERA_OPERATOR,
    LIGHTING_TECHNICIAN,
    VFX_SUPERVISOR,
    SPECIAL_EFFECTS_SUPERVISOR,
    ANIMATOR,
    MUSIC_COMPOSER
}