server:
  port: ${SERVER_PORT:9090}

security:
  jwt:
    secret-key: 406a970f5fdd329ef30bb1b0e6205f7692d69647322a926bd30ac84ab1c6b8fa
    expiration-time: 3600000

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
  application:
    name: movie-service
  datasource:
    url: jdbc:postgresql://localhost:5433/movies
    #    url: jdbc:postgresql://host.docker.internal:5433/movies
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    #    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
